image: otrs4ci

stages:
  - deploy

job_deploy_otrs_Znuny4OTRSTypePriorityBasedEscalation:
  stage: deploy
  script:
    - sh /sync_repo.sh git@github.com:znuny/Znuny4OTRS-TypePriorityBasedEscalation.git
